uartbinlib: examples/linux_posix_serial.c File Reference
linux_posix_serial.c File Reference
uartbinlib icin Linux POSIX serial port ornegi.
#include "uartbin.h"
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <termios.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct linux_uartbin
Tek Linux serial link icin uygulama tarafi durum.
Typedefs
typedef struct linux_uartbin linux_uartbin_t
Tek Linux serial link icin uygulama tarafi durum.
Functions
static uint32_t linux_millis (void)
CLOCK_MONOTONIC ile milisaniye timestamp dondur.
static speed_t linux_baud_to_speed (unsigned baud)
termios speed_t degeri sec.
static int linux_serial_configure (int fd, unsigned baud)
Serial portu 8N1 raw modda ve non-blocking calisacak sekilde ayarla.
static int linux_uartbin_write (const uint8_t *data, size_t len, void *user)
POSIX write kullanan uartbin TX hook.
static void linux_uartbin_on_packet (const uartbin_packet_t *packet, void *user)
CRC'den gecmis paketleri isleyen uygulama callback'i.
static void linux_uartbin_on_error (uartbin_error_t error, void *user)
Protokol hata callback'i.
static int linux_uartbin_init (linux_uartbin_t *port, const char *path, unsigned baud)
Linux adapter'i baslat.
static int linux_uartbin_run (linux_uartbin_t *port)
poll() tabanli RX ve retry servis dongusu.
int main (int argc, char **argv)
Detailed Description
uartbinlib icin Linux POSIX serial port ornegi.
Definition in file linux_posix_serial.c.
Typedef Documentation
linux_uartbin_t
typedef struct linux_uartbin linux_uartbin_t
Tek Linux serial link icin uygulama tarafi durum.
Examples
linux_posix_serial.c.
Function Documentation
linux_baud_to_speed()
speed_t linux_baud_to_speed (unsigned baud) static
termios speed_t degeri sec.
Ornek yalnizca yaygin baud rate degerlerini icerir. Gerekiyorsa tabloyu genislet.
Examples
linux_posix_serial.c.
Definition at line 78 of file linux_posix_serial.c.
Referenced by linux_serial_configure().
linux_millis()
uint32_t linux_millis (void) static
CLOCK_MONOTONIC ile milisaniye timestamp dondur.
Examples
linux_posix_serial.c.
Definition at line 61 of file linux_posix_serial.c.
Referenced by linux_uartbin_run().
linux_serial_configure()
int linux_serial_configure (int fd, unsigned baud) static
Serial portu 8N1 raw modda ve non-blocking calisacak sekilde ayarla.
Examples
linux_posix_serial.c.
Definition at line 99 of file linux_posix_serial.c.
References linux_baud_to_speed().
Referenced by linux_uartbin_init().
linux_uartbin_init()
int linux_uartbin_init (linux_uartbin_t * port, const char * path, unsigned baud) static
Linux adapter'i baslat.
Examples
linux_posix_serial.c.
Definition at line 198 of file linux_posix_serial.c.
References linux_uartbin::fd, linux_uartbin::link, linux_serial_configure(), linux_uartbin_on_error(), linux_uartbin_on_packet(), linux_uartbin_write(), uartbin_config::on_error, uartbin_config::on_packet, linux_uartbin::rx_payload, uartbin_config::rx_payload_buffer, uartbin_config::rx_payload_capacity, uartbin_config::rx_timeout_ms, uartbin_config::tx_retry_buffer, uartbin_config::tx_retry_capacity, linux_uartbin::tx_retry_frame, uartbin_config::tx_retry_max_retries, uartbin_config::tx_retry_timeout_ms, UARTBIN_DEFAULT_RETRY_MAX_RETRIES, UARTBIN_DEFAULT_RETRY_TIMEOUT_MS, uartbin_init(), uartbin_config::user, and uartbin_config::write.
Referenced by main().
linux_uartbin_on_error()
void linux_uartbin_on_error (uartbin_error_t error, void * user) static
Protokol hata callback'i.
Examples
linux_posix_serial.c.
Definition at line 187 of file linux_posix_serial.c.
References linux_uartbin::protocol_errors.
Referenced by linux_uartbin_init().
linux_uartbin_on_packet()
void linux_uartbin_on_packet (const uartbin_packet_t * packet, void * user) static
CRC'den gecmis paketleri isleyen uygulama callback'i.
Examples
linux_posix_serial.c.
Definition at line 167 of file linux_posix_serial.c.
References uartbin_packet::flags, linux_uartbin::link, uartbin_packet::payload_len, uartbin_packet::seq, uartbin_packet::type, UARTBIN_FLAG_EVENT, UARTBIN_FLAG_REQUEST, and uartbin_send_response().
Referenced by linux_uartbin_init().
linux_uartbin_run()
int linux_uartbin_run (linux_uartbin_t * port) static
poll() tabanli RX ve retry servis dongusu.
Examples
linux_posix_serial.c.
Definition at line 233 of file linux_posix_serial.c.
References linux_uartbin::fd, linux_uartbin::link, linux_millis(), linux_uartbin::rx_block, uartbin_feed_at(), uartbin_poll(), and uartbin_reset().
Referenced by main().
linux_uartbin_write()
int linux_uartbin_write (const uint8_t * data, size_t len, void * user) static
POSIX write kullanan uartbin TX hook.
Hook basari dondurmeden once tum byte'lari fd'ye kabul ettirir. Non-blocking fd EAGAIN dondururse kisa poll() beklemesi yapar.
Examples
linux_posix_serial.c.
Definition at line 133 of file linux_posix_serial.c.
References linux_uartbin::fd.
Referenced by linux_uartbin_init().
main()
int main (int argc, char ** argv)
Examples
linux_posix_serial.c.
Definition at line 268 of file linux_posix_serial.c.
References linux_uartbin::fd, linux_uartbin::link, linux_uartbin_init(), linux_uartbin_run(), and uartbin_send_event().