uartbinlib: examples/stm32_hal_interrupt.c File Reference
stm32_hal_interrupt.c File Reference
STM32 HAL interrupt-based RX adapter example for uartbinlib.
#include "uartbin.h"
Data Structures
struct stm32_uartbin_it
Application-side state for one interrupt-driven uartbin UART.
Macros
#define HAL_OK 0
Typedefs
typedef struct stm32_uartbin_it stm32_uartbin_it_t
Application-side state for one interrupt-driven uartbin UART.
Functions
uint32_t HAL_GetTick (void)
int HAL_UART_Transmit (UART_HandleTypeDef *huart, uint8_t *data, uint16_t size, uint32_t timeout)
int HAL_UART_Receive_IT (UART_HandleTypeDef *huart, uint8_t *data, uint16_t size)
int HAL_UART_AbortReceive_IT (UART_HandleTypeDef *huart)
static int stm32_uartbin_it_start_rx (stm32_uartbin_it_t *port)
Start the next one-byte interrupt receive operation.
static int stm32_uartbin_it_write (const uint8_t *data, size_t len, void *user)
uartbin TX hook using blocking HAL transmit.
static void stm32_uartbin_it_on_packet (const uartbin_packet_t *packet, void *user)
Application packet handler.
static void stm32_uartbin_it_on_error (uartbin_error_t error, void *user)
Protocol error callback.
void stm32_uartbin_it_init (stm32_uartbin_it_t *port, UART_HandleTypeDef *huart)
Initialize the interrupt adapter and arm the first RX byte.
void stm32_uartbin_it_rx_complete_callback (stm32_uartbin_it_t *port, UART_HandleTypeDef *huart)
Forward HAL_UART_RxCpltCallback() into uartbinlib.
void stm32_uartbin_it_error_callback (stm32_uartbin_it_t *port, UART_HandleTypeDef *huart)
Forward HAL_UART_ErrorCallback() into the adapter.
void stm32_uartbin_it_abort_complete_callback (stm32_uartbin_it_t *port, UART_HandleTypeDef *huart)
Forward HAL_UART_AbortReceiveCpltCallback() into the adapter.
void stm32_uartbin_it_poll (stm32_uartbin_it_t *port)
Periodic timeout service for the protocol parser.
Detailed Description
STM32 HAL interrupt-based RX adapter example for uartbinlib.
Definition in file stm32_hal_interrupt.c.
Macro Definition Documentation
HAL_OK
#define HAL_OK 0
Definition at line 64 of file stm32_hal_interrupt.c.
Typedef Documentation
stm32_uartbin_it_t
typedef struct stm32_uartbin_it stm32_uartbin_it_t
Application-side state for one interrupt-driven uartbin UART.
Examples
stm32_hal_interrupt.c.
Function Documentation
HAL_GetTick()
uint32_t HAL_GetTick (void) extern
HAL_UART_AbortReceive_IT()
int HAL_UART_AbortReceive_IT (UART_HandleTypeDef * huart) extern
Examples
stm32_hal_interrupt.c.
Referenced by stm32_uartbin_it_error_callback().
HAL_UART_Receive_IT()
int HAL_UART_Receive_IT (UART_HandleTypeDef * huart, uint8_t * data, uint16_t size) extern
Examples
stm32_hal_interrupt.c.
Referenced by stm32_uartbin_it_start_rx().
HAL_UART_Transmit()
int HAL_UART_Transmit (UART_HandleTypeDef * huart, uint8_t * data, uint16_t size, uint32_t timeout) extern
stm32_uartbin_it_abort_complete_callback()
void stm32_uartbin_it_abort_complete_callback (stm32_uartbin_it_t * port, UART_HandleTypeDef * huart)
Forward HAL_UART_AbortReceiveCpltCallback() into the adapter.
Some HAL versions complete abort asynchronously. This callback ensures RX is re-armed after the abort path finishes.
Examples
stm32_hal_interrupt.c.
Definition at line 219 of file stm32_hal_interrupt.c.
References stm32_uartbin_it::huart, and stm32_uartbin_it_start_rx().
stm32_uartbin_it_error_callback()
void stm32_uartbin_it_error_callback (stm32_uartbin_it_t * port, UART_HandleTypeDef * huart)
Forward HAL_UART_ErrorCallback() into the adapter.
On parity/framing/noise/overrun errors, discard the partial protocol frame, abort the HAL receive path, and try to arm reception again.
Examples
stm32_hal_interrupt.c.
Definition at line 203 of file stm32_hal_interrupt.c.
References stm32_uartbin_it::hal_rx_errors, HAL_UART_AbortReceive_IT(), stm32_uartbin_it::huart, stm32_uartbin_it::link, stm32_uartbin_it_start_rx(), and uartbin_reset().
stm32_uartbin_it_init()
void stm32_uartbin_it_init (stm32_uartbin_it_t * port, UART_HandleTypeDef * huart)
Initialize the interrupt adapter and arm the first RX byte.
Parameters
port Adapter instance owned by the application.
huart STM32 HAL UART handle.
Examples
stm32_hal_interrupt.c.
Definition at line 159 of file stm32_hal_interrupt.c.
References stm32_uartbin_it::hal_rx_errors, stm32_uartbin_it::huart, stm32_uartbin_it::link, uartbin_config::on_error, uartbin_config::on_packet, stm32_uartbin_it::protocol_errors, stm32_uartbin_it::rx_payload, uartbin_config::rx_payload_buffer, uartbin_config::rx_payload_capacity, uartbin_config::rx_timeout_ms, stm32_uartbin_it_on_error(), stm32_uartbin_it_on_packet(), stm32_uartbin_it_start_rx(), stm32_uartbin_it_write(), uartbin_init(), uartbin_config::user, and uartbin_config::write.
stm32_uartbin_it_on_error()
void stm32_uartbin_it_on_error (uartbin_error_t error, void * user) static
Protocol error callback.
Typical production code increments counters, records diagnostics, and may notify a supervisory task. The parser has already reset itself.
Examples
stm32_hal_interrupt.c.
Definition at line 145 of file stm32_hal_interrupt.c.
References stm32_uartbin_it::protocol_errors.
Referenced by stm32_uartbin_it_init().
stm32_uartbin_it_on_packet()
void stm32_uartbin_it_on_packet (const uartbin_packet_t * packet, void * user) static
Application packet handler.
This function is called only after the frame CRC succeeds. Firmware update code should process or copy packet here, not before CRC validation.
Examples
stm32_hal_interrupt.c.
Definition at line 125 of file stm32_hal_interrupt.c.
References uartbin_packet::type.
Referenced by stm32_uartbin_it_init().
stm32_uartbin_it_poll()
void stm32_uartbin_it_poll (stm32_uartbin_it_t * port)
Periodic timeout service for the protocol parser.
Call this from a main loop, RTOS task, or periodic timer context.
Examples
stm32_hal_interrupt.c.
Definition at line 231 of file stm32_hal_interrupt.c.
References HAL_GetTick(), stm32_uartbin_it::link, and uartbin_poll().
stm32_uartbin_it_rx_complete_callback()
void stm32_uartbin_it_rx_complete_callback (stm32_uartbin_it_t * port, UART_HandleTypeDef * huart)
Forward HAL_UART_RxCpltCallback() into uartbinlib.
The function feeds the received byte, then immediately arms the next byte. If re-arming fails, it resets the protocol parser so no partial frame leaks into the next successful receive operation.
Examples
stm32_hal_interrupt.c.
Definition at line 186 of file stm32_hal_interrupt.c.
References HAL_GetTick(), stm32_uartbin_it::hal_rx_errors, stm32_uartbin_it::huart, stm32_uartbin_it::link, stm32_uartbin_it::rx_byte, stm32_uartbin_it_start_rx(), uartbin_feed_byte_at(), and uartbin_reset().
stm32_uartbin_it_start_rx()
int stm32_uartbin_it_start_rx (stm32_uartbin_it_t * port) static
Start the next one-byte interrupt receive operation.
Parameters
port Adapter instance.
Returns
0 when HAL accepted the RX request, otherwise -1.
Examples
stm32_hal_interrupt.c.
Definition at line 96 of file stm32_hal_interrupt.c.
References HAL_OK, HAL_UART_Receive_IT(), stm32_uartbin_it::huart, and stm32_uartbin_it::rx_byte.
Referenced by stm32_uartbin_it_abort_complete_callback(), stm32_uartbin_it_error_callback(), stm32_uartbin_it_init(), and stm32_uartbin_it_rx_complete_callback().
stm32_uartbin_it_write()
int stm32_uartbin_it_write (const uint8_t * data, size_t len, void * user) static
uartbin TX hook using blocking HAL transmit.
Blocking transmit is used because uartbin_send() may call the write hook multiple times per frame. For non-blocking TX, replace this hook with a static application TX queue.
Examples
stm32_hal_interrupt.c.
Definition at line 108 of file stm32_hal_interrupt.c.
References HAL_OK, HAL_UART_Transmit(), and stm32_uartbin_it::huart.
Referenced by stm32_uartbin_it_init().