uartbinlib: examples/stm32_hal_dma_idle.c File Reference
stm32_hal_dma_idle.c File Reference
uartbinlib icin STM32 HAL DMA idle-line RX adapter ornegi.
#include "uartbin.h"
#include <string.h>
Data Structures
struct stm32_uartbin_dma
Tek DMA idle-line uartbin UART icin uygulama tarafi durum.
Macros
#define HAL_OK 0
#define DMA_IT_HT 0x00000004u
Typedefs
typedef struct UART_HandleTypeDef UART_HandleTypeDef
STM32 HAL DMA + idle-line RX ornegi.
typedef struct DMA_HandleTypeDef DMA_HandleTypeDef
typedef struct stm32_uartbin_dma stm32_uartbin_dma_t
Tek DMA idle-line uartbin UART icin uygulama tarafi durum.
Functions
uint32_t HAL_GetTick (void)
int HAL_UART_Transmit (UART_HandleTypeDef *huart, uint8_t *data, uint16_t size, uint32_t timeout)
int HAL_UARTEx_ReceiveToIdle_DMA (UART_HandleTypeDef *huart, uint8_t *data, uint16_t size)
int HAL_UART_AbortReceive (UART_HandleTypeDef *huart)
void __HAL_DMA_DISABLE_IT (DMA_HandleTypeDef *hdma, uint32_t interrupt)
static int stm32_uartbin_dma_start_rx (stm32_uartbin_dma_t *port)
ReceiveToIdle DMA reception baslat veya yeniden baslat.
static int stm32_uartbin_dma_write (const uint8_t *data, size_t len, void *user)
Blocking HAL transmit kullanan uartbin TX hook.
static void stm32_uartbin_dma_on_packet (const uartbin_packet_t *packet, void *user)
Uygulama packet handler'i.
static void stm32_uartbin_dma_on_error (uartbin_error_t error, void *user)
Protokol hata callback'i.
void stm32_uartbin_dma_init (stm32_uartbin_dma_t *port, UART_HandleTypeDef *huart, DMA_HandleTypeDef *hdma_rx)
DMA idle-line adapter'i baslat ve DMA RX'i arm et.
void stm32_uartbin_dma_rx_event_callback (stm32_uartbin_dma_t *port, UART_HandleTypeDef *huart, uint16_t size)
HAL_UARTEx_RxEventCallback() cagrimini uartbinlib'e ilet.
void stm32_uartbin_dma_error_callback (stm32_uartbin_dma_t *port, UART_HandleTypeDef *huart)
HAL_UART_ErrorCallback() cagrimini DMA adapter'a ilet.
void stm32_uartbin_dma_poll (stm32_uartbin_dma_t *port)
Protokol parser icin periyodik timeout servisi.
Detailed Description
uartbinlib icin STM32 HAL DMA idle-line RX adapter ornegi.
Definition in file stm32_hal_dma_idle.c.
Macro Definition Documentation
DMA_IT_HT
#define DMA_IT_HT 0x00000004u
Examples
stm32_hal_dma_idle.c.
Definition at line 63 of file stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_start_rx().
HAL_OK
#define HAL_OK 0
Examples
stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Definition at line 59 of file stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_start_rx(), stm32_uartbin_dma_write(), stm32_uartbin_it_start_rx(), and stm32_uartbin_it_write().
Typedef Documentation
DMA_HandleTypeDef
typedef struct DMA_HandleTypeDef DMA_HandleTypeDef
Examples
stm32_hal_dma_idle.c.
Definition at line 51 of file stm32_hal_dma_idle.c.
stm32_uartbin_dma_t
typedef struct stm32_uartbin_dma stm32_uartbin_dma_t
Tek DMA idle-line uartbin UART icin uygulama tarafi durum.
Examples
stm32_hal_dma_idle.c.
UART_HandleTypeDef
typedef struct UART_HandleTypeDef UART_HandleTypeDef
STM32 HAL DMA + idle-line RX ornegi.
STM32 HAL interrupt RX ornegi.
HAL_UARTEx_ReceiveToIdle_DMA kullanir ve alinan her blogu uartbin'e besler. TX, blocking HAL_UART_Transmit kullanir; cunku uartbin_send tek cerceve icin write hook'u birkac kez cagirir. Non-blocking transmit gerekiyorsa bunu kendi TX queue yapin ile degistir.
Gercek projede cihaz HAL header'ini include et, ornegin:
#include "stm32f4xx_hal.h"
TX notu: uartbin_send tek cerceve icin write hook'u birden fazla kez cagirir. Write hook donmeden once yazmayi bitirmeli veya byte'lari TX kuyruguna kopyalamalidir. Bu ornek bu nedenle blocking HAL_UART_Transmit kullanir.
Examples
stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Definition at line 50 of file stm32_hal_dma_idle.c.
Function Documentation
__HAL_DMA_DISABLE_IT()
void __HAL_DMA_DISABLE_IT (DMA_HandleTypeDef * hdma, uint32_t interrupt) extern
Examples
stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_start_rx().
HAL_GetTick()
uint32_t HAL_GetTick (void) extern
Examples
stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Referenced by stm32_uartbin_dma_poll(), stm32_uartbin_dma_rx_event_callback(), stm32_uartbin_it_poll(), and stm32_uartbin_it_rx_complete_callback().
HAL_UART_AbortReceive()
int HAL_UART_AbortReceive (UART_HandleTypeDef * huart) extern
Examples
stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_error_callback().
HAL_UART_Transmit()
int HAL_UART_Transmit (UART_HandleTypeDef * huart, uint8_t * data, uint16_t size, uint32_t timeout) extern
Examples
stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Referenced by stm32_uartbin_dma_write(), and stm32_uartbin_it_write().
HAL_UARTEx_ReceiveToIdle_DMA()
int HAL_UARTEx_ReceiveToIdle_DMA (UART_HandleTypeDef * huart, uint8_t * data, uint16_t size) extern
Examples
stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_start_rx().
stm32_uartbin_dma_error_callback()
void stm32_uartbin_dma_error_callback (stm32_uartbin_dma_t * port, UART_HandleTypeDef * huart)
HAL_UART_ErrorCallback() cagrimini DMA adapter'a ilet.
UART noise/framing/parity/overrun hatalarinda partial protokol cercevesini at, HAL receive yolunu abort et ve DMA idle-line reception'i yeniden baslat.
Examples
stm32_hal_dma_idle.c.
Definition at line 223 of file stm32_hal_dma_idle.c.
References stm32_uartbin_dma::hal_rx_errors, HAL_UART_AbortReceive(), stm32_uartbin_dma::huart, stm32_uartbin_dma::link, stm32_uartbin_dma_start_rx(), and uartbin_reset().
stm32_uartbin_dma_init()
void stm32_uartbin_dma_init (stm32_uartbin_dma_t * port, UART_HandleTypeDef * huart, DMA_HandleTypeDef * hdma_rx)
DMA idle-line adapter'i baslat ve DMA RX'i arm et.
Parameters
port Uygulamanin sahip oldugu adapter instance.
huart STM32 HAL UART handle.
hdma_rx UART RX icin STM32 HAL DMA handle.
Examples
stm32_hal_dma_idle.c.
Definition at line 164 of file stm32_hal_dma_idle.c.
References stm32_uartbin_dma::hal_rx_errors, stm32_uartbin_dma::hdma_rx, stm32_uartbin_dma::huart, stm32_uartbin_dma::link, uartbin_config::on_error, uartbin_config::on_packet, stm32_uartbin_dma::protocol_errors, stm32_uartbin_dma::rx_payload, uartbin_config::rx_payload_buffer, uartbin_config::rx_payload_capacity, uartbin_config::rx_timeout_ms, stm32_uartbin_dma_on_error(), stm32_uartbin_dma_on_packet(), stm32_uartbin_dma_start_rx(), stm32_uartbin_dma_write(), uartbin_init(), uartbin_config::user, and uartbin_config::write.
stm32_uartbin_dma_on_error()
void stm32_uartbin_dma_on_error (uartbin_error_t error, void * user) static
Protokol hata callback'i.
Bunu diagnostik, sayaclar ve opsiyonel link-level recovery politikasi icin kullan. HAL recovery, stm32_uartbin_dma_error_callback() ile yapilir.
Examples
stm32_hal_dma_idle.c.
Definition at line 149 of file stm32_hal_dma_idle.c.
References stm32_uartbin_dma::protocol_errors.
Referenced by stm32_uartbin_dma_init().
stm32_uartbin_dma_on_packet()
void stm32_uartbin_dma_on_packet (const uartbin_packet_t * packet, void * user) static
Uygulama packet handler'i.
Tam cerceve CRC'den gectikten sonra cagrilir. Payload pointer adapter RX payload buffer'ini isaret eder ve sonraki feed'e kadar gecerlidir.
Examples
stm32_hal_dma_idle.c.
Definition at line 136 of file stm32_hal_dma_idle.c.
Referenced by stm32_uartbin_dma_init().
stm32_uartbin_dma_poll()
void stm32_uartbin_dma_poll (stm32_uartbin_dma_t * port)
Protokol parser icin periyodik timeout servisi.
Bunu main loop, RTOS task veya periyodik timer context icinden cagir.
Examples
stm32_hal_dma_idle.c.
Definition at line 238 of file stm32_hal_dma_idle.c.
References HAL_GetTick(), stm32_uartbin_dma::link, and uartbin_poll().
stm32_uartbin_dma_rx_event_callback()
void stm32_uartbin_dma_rx_event_callback (stm32_uartbin_dma_t * port, UART_HandleTypeDef * huart, uint16_t size)
HAL_UARTEx_RxEventCallback() cagrimini uartbinlib'e ilet.
Parameters
port Adapter instance.
huart HAL tarafindan verilen UART handle.
size dma_rx_buffer icindeki gecerli byte sayisi.
Size kontrolu beklenmeyen HAL/kullanici hatalarina karsi korur. Blok beslendikten sonra fonksiyon ReceiveToIdle DMA'i hemen yeniden baslatir.
Examples
stm32_hal_dma_idle.c.
Definition at line 198 of file stm32_hal_dma_idle.c.
References stm32_uartbin_dma::dma_rx_buffer, HAL_GetTick(), stm32_uartbin_dma::hal_rx_errors, stm32_uartbin_dma::huart, stm32_uartbin_dma::link, stm32_uartbin_dma_start_rx(), uartbin_feed_at(), and uartbin_reset().
stm32_uartbin_dma_start_rx()
int stm32_uartbin_dma_start_rx (stm32_uartbin_dma_t * port) static
ReceiveToIdle DMA reception baslat veya yeniden baslat.
Bu adapter yalnizca idle veya buffer-complete event istedigi icin half-transfer interrupt'lari kapatilir. Uygulamanin half-transfer event'e ihtiyaci varsa yalnizca yeni alinan byte'lari besle ve DMA offset'lerini dikkatli takip et.
Examples
stm32_hal_dma_idle.c.
Definition at line 100 of file stm32_hal_dma_idle.c.
References __HAL_DMA_DISABLE_IT(), DMA_IT_HT, stm32_uartbin_dma::dma_rx_buffer, HAL_OK, HAL_UARTEx_ReceiveToIdle_DMA(), stm32_uartbin_dma::hdma_rx, and stm32_uartbin_dma::huart.
Referenced by stm32_uartbin_dma_error_callback(), stm32_uartbin_dma_init(), and stm32_uartbin_dma_rx_event_callback().
stm32_uartbin_dma_write()
int stm32_uartbin_dma_write (const uint8_t * data, size_t len, void * user) static
Blocking HAL transmit kullanan uartbin TX hook.
uartbin_send() coklu write sozlesmesi ile dogru calismasi icin blocking transmit kullanilir. Non-blocking sistemlerde statik TX queue ile degistir.
Examples
stm32_hal_dma_idle.c.
Definition at line 119 of file stm32_hal_dma_idle.c.
References HAL_OK, HAL_UART_Transmit(), and stm32_uartbin_dma::huart.
Referenced by stm32_uartbin_dma_init().