uartbinlib: src/uartbin.c File Reference
uartbin.c File Reference
uartbin binary UART cerceve parser ve sender implementasyonu.
#include "uartbin.h"
#include <string.h>
Enumerations
enum {
UARTBIN_STATE_SOF0 = 0 , UARTBIN_STATE_SOF1 , UARTBIN_STATE_HEADER , UARTBIN_STATE_PAYLOAD ,
UARTBIN_STATE_CRC
}
Ic RX parser durumlari.
Functions
static uint16_t uartbin_get_u16_le (const uint8_t *data)
Little-endian 16-bit deger oku.
static void uartbin_put_u16_le (uint8_t *data, uint16_t value)
Little-endian 16-bit deger yaz.
static void uartbin_reset_rx (uartbin_t *ctx)
Parser bookkeeping durumunu SOF arama durumuna resetle.
static void uartbin_report_error (uartbin_t *ctx, uartbin_error_t error)
Uygulama callback kaydettiyse parser hatasini ilet.
static uartbin_status_t uartbin_write_all (uartbin_t *ctx, const uint8_t *data, size_t len)
Ayarlanan write hook'u tek bitisik byte araligi icin cagir.
static int uartbin_rx_active (const uartbin_t *ctx)
RX parser'in su anda cerceve icinde olup olmadigini test et.
static size_t uartbin_frame_len (uint16_t payload_len)
static uartbin_status_t uartbin_build_frame (uint8_t *frame, size_t frame_capacity, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t *payload, uint16_t payload_len, size_t *frame_len)
static void uartbin_clear_retry (uartbin_t *ctx)
static int uartbin_retry_enabled (const uartbin_t *ctx)
static uartbin_status_t uartbin_check_retry_start (const uartbin_t *ctx, uint16_t payload_len)
static uartbin_status_t uartbin_start_retry (uartbin_t *ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t *payload, uint16_t payload_len)
static void uartbin_poll_retry (uartbin_t *ctx, uint32_t now_ms)
static void uartbin_poll_rx_timeout (uartbin_t *ctx, uint32_t now_ms)
void uartbin_init (uartbin_t *ctx, const uartbin_config_t *config)
uartbin context baslat.
void uartbin_reset (uartbin_t *ctx)
Yalnizca RX parser durumunu resetle.
void uartbin_cancel_retry (uartbin_t *ctx)
Pending otomatik retry durumunu iptal et.
uint16_t uartbin_crc16_ccitt (const uint8_t *data, size_t len, uint16_t seed)
CRC-16/CCITT-FALSE degerini guncelle.
uartbin_status_t uartbin_send (uartbin_t *ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t *payload, uint16_t payload_len)
Tek cerceveli paketi olustur ve gonder.
uint16_t uartbin_next_seq (uartbin_t *ctx)
Bu context icin sonraki sifir olmayan TX sira numarasini dondur.
uartbin_status_t uartbin_send_request (uartbin_t *ctx, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile yeni request gonder.
uartbin_status_t uartbin_send_response (uartbin_t *ctx, const uartbin_packet_t *request, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Alinan paketteki sira numarasini kullanarak response gonder.
uartbin_status_t uartbin_send_event (uartbin_t *ctx, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile unsolicited event gonder.
void uartbin_feed (uartbin_t *ctx, const uint8_t *data, size_t len)
Alinan byte'lari timeout timestamp guncellemesi olmadan besle.
void uartbin_feed_byte (uartbin_t *ctx, uint8_t byte)
Tek alinan byte'i timeout timestamp guncellemesi olmadan besle.
void uartbin_feed_at (uartbin_t *ctx, const uint8_t *data, size_t len, uint32_t now_ms)
Alinan byte'lari gecerli uygulama timestamp degeri ile besle.
void uartbin_poll (uartbin_t *ctx, uint32_t now_ms)
RX timeout ve opsiyonel TX retry zamanlamasini servis et.
void uartbin_feed_byte_at (uartbin_t *ctx, uint8_t byte, uint32_t now_ms)
RX state machine'e tek byte besle.
Detailed Description
uartbin binary UART cerceve parser ve sender implementasyonu.
Implementasyon bilerek kucuk ve deterministik tutulmustur:
dinamik bellek yok,
platform cagrisi yok,
tek gecisli RX parser,
payload byte'lari geldikce CRC guncellenir,
uygulama paketi yalnizca CRC basarili olduktan sonra gorur.
Definition in file uartbin.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Ic RX parser durumlari.
Parser iki byte'lik SOF dizisini arar, sonra sabit header, payload ve CRC alanlarini alir. Her parse hatasinda SOF arama durumuna resetlenir; boylece sonraki byte'lar linki yeniden senkronlayabilir.
Enumerator
UARTBIN_STATE_SOF0
UARTBIN_SOF0 bekleniyor.
UARTBIN_STATE_SOF1
UARTBIN_SOF0 gorulduktan sonra UARTBIN_SOF1 bekleniyor.
UARTBIN_STATE_HEADER
Sabit boyutlu header aliniyor.
UARTBIN_STATE_PAYLOAD
Payload byte'lari kullanici RX buffer'ina aliniyor.
UARTBIN_STATE_CRC
Iki byte'lik CRC alani aliniyor.
Definition at line 24 of file uartbin.c.
Function Documentation
uartbin_build_frame()
uartbin_status_t uartbin_build_frame (uint8_t * frame, size_t frame_capacity, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t * payload, uint16_t payload_len, size_t * frame_len) static
Definition at line 133 of file uartbin.c.
References uartbin_crc16_ccitt(), UARTBIN_EINVAL, UARTBIN_EPAYLOAD_TOO_LONG, uartbin_frame_len(), UARTBIN_HEADER_SIZE, UARTBIN_OK, uartbin_put_u16_le(), UARTBIN_SOF0, UARTBIN_SOF1, and UARTBIN_VERSION.
Referenced by uartbin_start_retry().
uartbin_cancel_retry()
void uartbin_cancel_retry (uartbin_t * ctx)
Pending otomatik retry durumunu iptal et.
RX parsing resetlenmez ve bir sey gonderilmez. Uygulama response gelmeden bir istegi bilincli olarak terk etmek istediginde kullanislidir.
Parameters
ctx Baslatilmis context.
Definition at line 313 of file uartbin.c.
References uartbin_clear_retry().
uartbin_check_retry_start()
uartbin_status_t uartbin_check_retry_start (const uartbin_t * ctx, uint16_t payload_len) static
Definition at line 187 of file uartbin.c.
References uartbin::cfg, uartbin::retry_active, uartbin_config::tx_retry_buffer, uartbin_config::tx_retry_capacity, UARTBIN_EBUSY, UARTBIN_ENO_BUFFER, UARTBIN_EPAYLOAD_TOO_LONG, uartbin_frame_len(), UARTBIN_OK, and uartbin_retry_enabled().
Referenced by uartbin_send_event(), uartbin_send_request(), and uartbin_start_retry().
uartbin_clear_retry()
void uartbin_clear_retry (uartbin_t * ctx) static
Definition at line 172 of file uartbin.c.
References uartbin::retry_active, uartbin::retry_count, uartbin::retry_frame_len, uartbin::retry_last_tx_time_ms, uartbin::retry_seq, and uartbin::retry_timer_started.
Referenced by uartbin_cancel_retry(), uartbin_feed_byte_at(), uartbin_poll_retry(), uartbin_send_event(), and uartbin_send_request().
uartbin_crc16_ccitt()
uint16_t uartbin_crc16_ccitt (const uint8_t * data, size_t len, uint16_t seed)
CRC-16/CCITT-FALSE degerini guncelle.
Polynomial: 0x1021. Kutuphane cerceveler icin 0xFFFF seed kullanir.
Parameters
data Giris byte'lari. Yalnizca len 0 iken NULL olabilir.
len Giris byte sayisi.
seed Baslangic/akan CRC degeri.
Returns
Guncellenmis CRC degeri.
Definition at line 320 of file uartbin.c.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
uartbin_feed()
void uartbin_feed (uartbin_t * ctx, const uint8_t * data, size_t len)
Alinan byte'lari timeout timestamp guncellemesi olmadan besle.
Zaman asimi yonetimi acikken uartbin_feed_at() tercih edilmelidir.
Parameters
ctx Baslatilmis context.
data Alinan byte buffer'i.
len Alinan byte sayisi.
Definition at line 490 of file uartbin.c.
References uartbin_feed_byte().
uartbin_feed_at()
void uartbin_feed_at (uartbin_t * ctx, const uint8_t * data, size_t len, uint32_t now_ms)
Alinan byte'lari gecerli uygulama timestamp degeri ile besle.
Parameters
ctx Baslatilmis context.
data Alinan byte buffer'i.
len Alinan byte sayisi.
now_ms HAL_GetTick() gibi monotonic milisaniye timestamp.
Definition at line 506 of file uartbin.c.
References uartbin_feed_byte_at().
Referenced by linux_uartbin_run(), and stm32_uartbin_dma_rx_event_callback().
uartbin_feed_byte()
void uartbin_feed_byte (uartbin_t * ctx, uint8_t byte)
Tek alinan byte'i timeout timestamp guncellemesi olmadan besle.
Zaman asimi yonetimi acikken uartbin_feed_byte_at() tercih edilmelidir.
Parameters
ctx Baslatilmis context.
byte Alinan byte.
Definition at line 501 of file uartbin.c.
References uartbin::last_rx_time_ms, and uartbin_feed_byte_at().
Referenced by uartbin_feed().
uartbin_feed_byte_at()
void uartbin_feed_byte_at (uartbin_t * ctx, uint8_t byte, uint32_t now_ms)
RX state machine'e tek byte besle.
Tek alinan byte'i gecerli uygulama timestamp degeri ile besle.
Bu internal state machine parser'in merkezidir. Public fonksiyon tum mantigi tek yerde tutar; boylece block ve byte feed yollari ayni davranir.
RX state machine'e tek byte besle.
Parameters
ctx Baslatilmis context.
byte Alinan byte.
now_ms HAL_GetTick() gibi monotonic milisaniye timestamp.
Definition at line 533 of file uartbin.c.
References uartbin::cfg, uartbin::crc, uartbin::crc_bytes, uartbin::crc_pos, uartbin_packet::flags, uartbin::header, uartbin::header_pos, uartbin::last_rx_time_ms, uartbin_config::on_packet, uartbin_packet::payload, uartbin::payload_len, uartbin_packet::payload_len, uartbin::payload_pos, uartbin::retry_active, uartbin::retry_seq, uartbin_config::rx_payload_buffer, uartbin_config::rx_payload_capacity, uartbin_packet::seq, uartbin::state, uartbin_packet::type, uartbin_clear_retry(), uartbin_crc16_ccitt(), UARTBIN_CRC_SIZE, UARTBIN_ERROR_BAD_LENGTH, UARTBIN_ERROR_BAD_VERSION, UARTBIN_ERROR_CRC, UARTBIN_ERROR_RX_OVERFLOW, UARTBIN_FLAG_RESPONSE, uartbin_get_u16_le(), UARTBIN_HEADER_SIZE, uartbin_poll_rx_timeout(), uartbin_report_error(), uartbin_reset_rx(), UARTBIN_SOF0, UARTBIN_SOF1, UARTBIN_STATE_CRC, UARTBIN_STATE_HEADER, UARTBIN_STATE_PAYLOAD, UARTBIN_STATE_SOF0, UARTBIN_STATE_SOF1, UARTBIN_VERSION, and uartbin_config::user.
Referenced by stm32_uartbin_it_rx_complete_callback(), uartbin_feed_at(), and uartbin_feed_byte().
uartbin_frame_len()
size_t uartbin_frame_len (uint16_t payload_len) static
Definition at line 128 of file uartbin.c.
References UARTBIN_MAX_FRAME_OVERHEAD.
Referenced by uartbin_build_frame(), and uartbin_check_retry_start().
uartbin_get_u16_le()
uint16_t uartbin_get_u16_le (const uint8_t * data) static
Little-endian 16-bit deger oku.
Parameters
data En az iki byte'a pointer.
Returns
Cozulmus 16-bit deger.
Definition at line 47 of file uartbin.c.
Referenced by uartbin_feed_byte_at().
uartbin_init()
void uartbin_init (uartbin_t * ctx, const uartbin_config_t * config)
uartbin context baslat.
Parameters
ctx Baslatilacak context. Link kullanildigi surece gecerli kalmalidir.
config ctx icine kopyalanacak konfigurasyon.
Definition at line 295 of file uartbin.c.
References uartbin::cfg, and uartbin_reset_rx().
Referenced by linux_uartbin_init(), stm32_uartbin_dma_init(), and stm32_uartbin_it_init().
uartbin_next_seq()
uint16_t uartbin_next_seq (uartbin_t * ctx)
Bu context icin sonraki sifir olmayan TX sira numarasini dondur.
Bu daha cok otomatik uretilecek request'i gondermeden once takip etmek isteyen uygulamalar icin kullanislidir. Request/event yardimcilari bunu internal olarak cagirir; cogu uygulamanin dogrudan kullanmasi gerekmez.
Parameters
ctx Baslatilmis context.
Returns
Sonraki sira numarasi; ctx NULL ise 0.
Definition at line 385 of file uartbin.c.
References uartbin::tx_seq.
Referenced by uartbin_send_event(), and uartbin_send_request().
uartbin_poll()
void uartbin_poll (uartbin_t * ctx, uint32_t now_ms)
RX timeout ve opsiyonel TX retry zamanlamasini servis et.
uartbin_config::rx_timeout_ms veya uartbin_config::tx_retry_timeout_ms sifir disi oldugunda bunu main loop veya scheduler icinden periyodik cagir. Feed fonksiyonlari yalnizca RX timeout servis eder; otomatik TX retry bu acik poll cagrisi ile surulur.
Parameters
ctx Baslatilmis context.
now_ms Monotonic milisaniye timestamp.
Definition at line 517 of file uartbin.c.
References uartbin_poll_retry(), and uartbin_poll_rx_timeout().
Referenced by linux_uartbin_run(), stm32_uartbin_dma_poll(), and stm32_uartbin_it_poll().
uartbin_poll_retry()
void uartbin_poll_retry (uartbin_t * ctx, uint32_t now_ms) static
Definition at line 244 of file uartbin.c.
References uartbin::cfg, uartbin::retry_active, uartbin::retry_count, uartbin::retry_frame_len, uartbin::retry_last_tx_time_ms, uartbin::retry_timer_started, uartbin_config::tx_retry_buffer, uartbin_config::tx_retry_max_retries, uartbin_clear_retry(), UARTBIN_ERROR_RETRY_EXHAUSTED, UARTBIN_ERROR_RETRY_WRITE, UARTBIN_OK, uartbin_report_error(), uartbin_retry_enabled(), and uartbin_write_all().
Referenced by uartbin_poll().
uartbin_poll_rx_timeout()
void uartbin_poll_rx_timeout (uartbin_t * ctx, uint32_t now_ms) static
Definition at line 279 of file uartbin.c.
References uartbin::cfg, uartbin::last_rx_time_ms, uartbin_config::rx_timeout_ms, UARTBIN_ERROR_TIMEOUT, uartbin_report_error(), uartbin_reset_rx(), and uartbin_rx_active().
Referenced by uartbin_feed_byte_at(), and uartbin_poll().
uartbin_put_u16_le()
void uartbin_put_u16_le (uint8_t * data, uint16_t value) static
Little-endian 16-bit deger yaz.
Parameters
data En az iki yazilabilir byte'a pointer.
value Kodlanacak deger.
Definition at line 58 of file uartbin.c.
Referenced by uartbin_build_frame(), and uartbin_send().
uartbin_report_error()
void uartbin_report_error (uartbin_t * ctx, uartbin_error_t error) static
Uygulama callback kaydettiyse parser hatasini ilet.
Parameters
ctx Hatayi algilayan context.
error Bildirilecek hata kodu.
Definition at line 89 of file uartbin.c.
References uartbin::cfg, uartbin_config::on_error, and uartbin_config::user.
Referenced by uartbin_feed_byte_at(), uartbin_poll_retry(), and uartbin_poll_rx_timeout().
uartbin_reset()
void uartbin_reset (uartbin_t * ctx)
Yalnizca RX parser durumunu resetle.
Platform UART hatalari, manuel abort veya link recovery olaylarindan sonra kullan. Konfigurasyon ve callback'ler korunur.
Parameters
ctx Resetlenecek context.
Definition at line 306 of file uartbin.c.
References uartbin_reset_rx().
Referenced by linux_uartbin_run(), stm32_uartbin_dma_error_callback(), stm32_uartbin_dma_rx_event_callback(), stm32_uartbin_it_error_callback(), and stm32_uartbin_it_rx_complete_callback().
uartbin_reset_rx()
void uartbin_reset_rx (uartbin_t * ctx) static
Parser bookkeeping durumunu SOF arama durumuna resetle.
Kullanici konfigurasyonunu degistirmez ve uygulama payload buffer'ini temizlemez. Buffer icerigi bir sonraki basarili packet callback'e kadar gecersiz kabul edilir.
Parameters
ctx RX durumu resetlenecek context.
Definition at line 73 of file uartbin.c.
References uartbin::crc, uartbin::crc_pos, uartbin::header_pos, uartbin::payload_len, uartbin::payload_pos, uartbin::state, and UARTBIN_STATE_SOF0.
Referenced by uartbin_feed_byte_at(), uartbin_init(), uartbin_poll_rx_timeout(), and uartbin_reset().
uartbin_retry_enabled()
int uartbin_retry_enabled (const uartbin_t * ctx) static
Definition at line 182 of file uartbin.c.
References uartbin::cfg, uartbin_config::tx_retry_max_retries, and uartbin_config::tx_retry_timeout_ms.
Referenced by uartbin_check_retry_start(), uartbin_poll_retry(), and uartbin_start_retry().
uartbin_rx_active()
int uartbin_rx_active (const uartbin_t * ctx) static
RX parser'in su anda cerceve icinde olup olmadigini test et.
Parameters
ctx Incelenecek context.
Returns
Zaman asimi yonetimi parser'i aktif kabul etmeli ise sifir disi.
Definition at line 123 of file uartbin.c.
References uartbin::state, and UARTBIN_STATE_SOF0.
Referenced by uartbin_poll_rx_timeout().
uartbin_send()
uartbin_status_t uartbin_send (uartbin_t * ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t * payload, uint16_t payload_len)
Tek cerceveli paketi olustur ve gonder.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan paket tipi.
flags Uygulama tarafindan tanimlanan flag'ler.
seq Uygulama tarafindan tanimlanan sira numarasi.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 339 of file uartbin.c.
References uartbin_crc16_ccitt(), UARTBIN_CRC_SIZE, UARTBIN_EINVAL, UARTBIN_HEADER_SIZE, UARTBIN_OK, uartbin_put_u16_le(), UARTBIN_SOF0, UARTBIN_SOF1, UARTBIN_VERSION, and uartbin_write_all().
Referenced by uartbin_send_event(), uartbin_send_request(), and uartbin_send_response().
uartbin_send_event()
uartbin_status_t uartbin_send_event (uartbin_t * ctx, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile unsolicited event gonder.
Yardimci flags icine UARTBIN_FLAG_EVENT OR eder ve context'in internal sira sayacini kullanir. Peer event'i ACK'liyorsa response icinde bu paketin sira numarasini geri yazmalidir.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan event tipi.
flags Event flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 454 of file uartbin.c.
References uartbin_check_retry_start(), uartbin_clear_retry(), UARTBIN_EINVAL, UARTBIN_FLAG_EVENT, uartbin_next_seq(), UARTBIN_OK, uartbin_send(), and uartbin_start_retry().
Referenced by main().
uartbin_send_request()
uartbin_status_t uartbin_send_request (uartbin_t * ctx, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile yeni request gonder.
Yardimci flags icine UARTBIN_FLAG_REQUEST OR eder ve context'in internal sira sayacini kullanir. Bu paketi cevaplamak icin response yardimcisini kullan.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan request tipi.
flags Request flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 399 of file uartbin.c.
References uartbin_check_retry_start(), uartbin_clear_retry(), UARTBIN_EINVAL, UARTBIN_FLAG_REQUEST, uartbin_next_seq(), UARTBIN_OK, uartbin_send(), and uartbin_start_retry().
uartbin_send_response()
uartbin_status_t uartbin_send_response (uartbin_t * ctx, const uartbin_packet_t * request, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Alinan paketteki sira numarasini kullanarak response gonder.
Yardimci flags icine UARTBIN_FLAG_RESPONSE OR eder ve request->seq degerini geri yazar. Context sira sayacini ilerletmez.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
request Cevaplanan paket.
type Uygulama tarafindan tanimlanan response tipi.
flags Response flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 435 of file uartbin.c.
References uartbin_packet::seq, UARTBIN_EINVAL, UARTBIN_FLAG_RESPONSE, and uartbin_send().
Referenced by linux_uartbin_on_packet().
uartbin_start_retry()
uartbin_status_t uartbin_start_retry (uartbin_t * ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t * payload, uint16_t payload_len) static
Definition at line 205 of file uartbin.c.
References uartbin::cfg, uartbin::retry_active, uartbin::retry_count, uartbin::retry_frame_len, uartbin::retry_last_tx_time_ms, uartbin::retry_seq, uartbin::retry_timer_started, uartbin_config::tx_retry_buffer, uartbin_config::tx_retry_capacity, uartbin_build_frame(), uartbin_check_retry_start(), UARTBIN_OK, and uartbin_retry_enabled().
Referenced by uartbin_send_event(), and uartbin_send_request().
uartbin_write_all()
uartbin_status_t uartbin_write_all (uartbin_t * ctx, const uint8_t * data, size_t len) static
Ayarlanan write hook'u tek bitisik byte araligi icin cagir.
Parameters
ctx Baslatilmis context.
data Yazilacak veri.
len Yazilacak byte sayisi.
Returns
Basarida UARTBIN_OK veya anlik write/konfigurasyon hatasi.
Definition at line 104 of file uartbin.c.
References uartbin::cfg, UARTBIN_EINVAL, UARTBIN_EWRITE, UARTBIN_OK, uartbin_config::user, and uartbin_config::write.
Referenced by uartbin_poll_retry(), and uartbin_send().