uartbinlib: include/uartbin.h File Reference
uartbin.h File Reference
Platformdan bagimsiz binary UART cerceveleme kutuphanesi.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct uartbin_packet
Uygulamaya iletilen CRC kontrolunden gecmis paket.
struct uartbin_config
uartbin context baslatmak icin kullanilan konfigurasyon.
struct uartbin
Tek uartbin linki icin runtime durum.
Macros
#define UARTBINLIB_VERSION_MAJOR 1u
Kutuphane semantik versiyon major degeri.
#define UARTBINLIB_VERSION_MINOR 0u
Kutuphane semantik versiyon minor degeri.
#define UARTBINLIB_VERSION_PATCH 0u
Kutuphane semantik versiyon patch degeri.
#define UARTBINLIB_VERSION_STRING "V1.0.0"
Kutuphane semantik versiyon metni.
#define UARTBIN_VERSION 1u
Her cerceve header'inda tasinan protokol surumu.
#define UARTBIN_SOF0 0xA5u
Start-of-frame dizisinin ilk byte'i.
#define UARTBIN_SOF1 0x5Au
Start-of-frame dizisinin ikinci byte'i.
#define UARTBIN_HEADER_SIZE 8u
Iki SOF byte'indan sonraki header boyutu, byte cinsinden.
#define UARTBIN_CRC_SIZE 2u
CRC alan boyutu, byte cinsinden.
#define UARTBIN_MAX_FRAME_OVERHEAD (2u + UARTBIN_HEADER_SIZE + UARTBIN_CRC_SIZE)
Her payload etrafina eklenen byte'lar: SOF + header + CRC.
#define UARTBIN_DEFAULT_RETRY_TIMEOUT_MS 100u
Uygulamalarin config icinde kullanabilecegi varsayilan retry timeout.
#define UARTBIN_DEFAULT_RETRY_MAX_RETRIES 3u
Uygulamalarin config icinde kullanabilecegi varsayilan retry sayisi.
#define UARTBIN_FLAG_REQUEST 0x01u
uartbin_send_request() tarafindan set edilen flag biti.
#define UARTBIN_FLAG_RESPONSE 0x02u
uartbin_send_response() tarafindan set edilen flag biti.
#define UARTBIN_FLAG_EVENT 0x04u
uartbin_send_event() tarafindan set edilen flag biti.
Typedefs
typedef enum uartbin_status uartbin_status_t
Hemen basarisiz olabilen API cagrilari icin donus durumlari.
typedef enum uartbin_error uartbin_error_t
uartbin_error_fn ile iletilen parser/runtime hatalari.
typedef struct uartbin_packet uartbin_packet_t
Uygulamaya iletilen CRC kontrolunden gecmis paket.
typedef int(* uartbin_write_fn) (const uint8_t *data, size_t len, void *user)
uartbin_send() tarafindan kullanilan platform write hook'u.
typedef void(* uartbin_packet_fn) (const uartbin_packet_t *packet, void *user)
Tam cerceve CRC dogrulamasindan gecince cagrilir.
typedef void(* uartbin_error_fn) (uartbin_error_t error, void *user)
Parser protokol hatasi veya timeout algiladiginda cagrilir.
typedef struct uartbin_config uartbin_config_t
uartbin context baslatmak icin kullanilan konfigurasyon.
typedef struct uartbin uartbin_t
Tek uartbin linki icin runtime durum.
Enumerations
enum uartbin_status {
UARTBIN_OK = 0 , UARTBIN_EINVAL = -1 , UARTBIN_EWRITE = -2 , UARTBIN_EPAYLOAD_TOO_LONG = -3 ,
UARTBIN_ENO_BUFFER = -4 , UARTBIN_EBUSY = -5
}
Hemen basarisiz olabilen API cagrilari icin donus durumlari.
enum uartbin_error {
UARTBIN_ERROR_BAD_VERSION = 1 , UARTBIN_ERROR_BAD_LENGTH , UARTBIN_ERROR_CRC , UARTBIN_ERROR_RX_OVERFLOW ,
UARTBIN_ERROR_TIMEOUT , UARTBIN_ERROR_RETRY_EXHAUSTED , UARTBIN_ERROR_RETRY_WRITE
}
uartbin_error_fn ile iletilen parser/runtime hatalari.
Functions
void uartbin_init (uartbin_t *ctx, const uartbin_config_t *config)
uartbin context baslat.
void uartbin_reset (uartbin_t *ctx)
Yalnizca RX parser durumunu resetle.
void uartbin_cancel_retry (uartbin_t *ctx)
Pending otomatik retry durumunu iptal et.
uartbin_status_t uartbin_send (uartbin_t *ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t *payload, uint16_t payload_len)
Tek cerceveli paketi olustur ve gonder.
uint16_t uartbin_next_seq (uartbin_t *ctx)
Bu context icin sonraki sifir olmayan TX sira numarasini dondur.
uartbin_status_t uartbin_send_request (uartbin_t *ctx, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile yeni request gonder.
uartbin_status_t uartbin_send_response (uartbin_t *ctx, const uartbin_packet_t *request, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Alinan paketteki sira numarasini kullanarak response gonder.
uartbin_status_t uartbin_send_event (uartbin_t *ctx, uint8_t type, uint8_t flags, const uint8_t *payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile unsolicited event gonder.
void uartbin_feed (uartbin_t *ctx, const uint8_t *data, size_t len)
Alinan byte'lari timeout timestamp guncellemesi olmadan besle.
void uartbin_feed_byte (uartbin_t *ctx, uint8_t byte)
Tek alinan byte'i timeout timestamp guncellemesi olmadan besle.
void uartbin_feed_at (uartbin_t *ctx, const uint8_t *data, size_t len, uint32_t now_ms)
Alinan byte'lari gecerli uygulama timestamp degeri ile besle.
void uartbin_feed_byte_at (uartbin_t *ctx, uint8_t byte, uint32_t now_ms)
Tek alinan byte'i gecerli uygulama timestamp degeri ile besle.
void uartbin_poll (uartbin_t *ctx, uint32_t now_ms)
RX timeout ve opsiyonel TX retry zamanlamasini servis et.
uint16_t uartbin_crc16_ccitt (const uint8_t *data, size_t len, uint16_t seed)
CRC-16/CCITT-FALSE degerini guncelle.
Detailed Description
Platformdan bagimsiz binary UART cerceveleme kutuphanesi.
uartbinlib, UART gibi byte akislari uzerinden degisken uzunluklu binary paket gonderip almak icin kucuk bir C API sunar. Cekirdek kutuphane HAL, RTOS, interrupt, DMA veya dinamik bellek bagimliligi tasimaz. Tum buffer'lar uygulamaya aittir; kutuphane hedef platforma hook ve callback'lerle baglanir.
Genel Bakis
uartbinlib binary payload'lari su sekilde cerceveler:
SOF(2) | version(1) | type(1) | flags(1) | reserved(1) |
seq(2) | payload_len(2) | payload(N) | crc16(2)
Alici, tam payload'u kullanicinin verdigi statik buffer icinde saklar. Paket callback'i yalnizca tum cerceve CRC dogrulamasindan gectikten sonra cagrilir. Bu tasarim API'yi basit tutar ve gomulu komut, telemetri, konfigurasyon ve firmware parca protokolleri icin uygun hale getirir.
Uygulamalar acik sira numarasi ile dusuk seviye uartbin_send() API'sini veya daha ust seviye request/response/event yardimcilarini kullanabilir. Yardimcilar context basina otomatik sira sayaci tutar, response icin sira numarasini geri yazar ve opsiyonel olarak eslesen response gelene kadar request/event cercevelerini retry edebilir.
Bellek Modeli
Kutuphane bellek ayirmaz. Uygulama sunlari verir:
kalici bir uartbin_t context,
statik RX payload buffer,
opsiyonel statik TX retry frame buffer,
TX icin write hook,
packet ve error callback'leri.
Zaman Asimi Modeli
uartbin_config::rx_timeout_ms degerini sifir disi ayarla ve uartbin_poll() fonksiyonunu periyodik cagir. Timestamp alan feed fonksiyonlari da her byte/block kabul etmeden once RX timeout kontrolu yapar. Ayni uartbin_poll() cagrisi, uartbin_config::tx_retry_timeout_ms ayarlandiginda opsiyonel TX retry zamanlamasini surer.
STM32 Entegrasyonu
Portable cekirdek STM32 header'lari icermez. Interrupt ve DMA idle-line adapter kaliplari ile HAL hata recovery icin examples/ altindaki dosyalara bak.
Definition in file uartbin.h.
Macro Definition Documentation
UARTBIN_CRC_SIZE
#define UARTBIN_CRC_SIZE 2u
CRC alan boyutu, byte cinsinden.
Definition at line 89 of file uartbin.h.
Referenced by uartbin_feed_byte_at(), and uartbin_send().
UARTBIN_DEFAULT_RETRY_MAX_RETRIES
#define UARTBIN_DEFAULT_RETRY_MAX_RETRIES 3u
Uygulamalarin config icinde kullanabilecegi varsayilan retry sayisi.
Examples
linux_posix_serial.c.
Definition at line 101 of file uartbin.h.
Referenced by linux_uartbin_init().
UARTBIN_DEFAULT_RETRY_TIMEOUT_MS
#define UARTBIN_DEFAULT_RETRY_TIMEOUT_MS 100u
Uygulamalarin config icinde kullanabilecegi varsayilan retry timeout.
Examples
linux_posix_serial.c.
Definition at line 96 of file uartbin.h.
Referenced by linux_uartbin_init().
UARTBIN_FLAG_EVENT
#define UARTBIN_FLAG_EVENT 0x04u
uartbin_send_event() tarafindan set edilen flag biti.
Examples
linux_posix_serial.c.
Definition at line 111 of file uartbin.h.
Referenced by linux_uartbin_on_packet(), and uartbin_send_event().
UARTBIN_FLAG_REQUEST
#define UARTBIN_FLAG_REQUEST 0x01u
uartbin_send_request() tarafindan set edilen flag biti.
Examples
linux_posix_serial.c.
Definition at line 105 of file uartbin.h.
Referenced by linux_uartbin_on_packet(), and uartbin_send_request().
UARTBIN_FLAG_RESPONSE
#define UARTBIN_FLAG_RESPONSE 0x02u
uartbin_send_response() tarafindan set edilen flag biti.
Definition at line 108 of file uartbin.h.
Referenced by uartbin_feed_byte_at(), and uartbin_send_response().
UARTBIN_HEADER_SIZE
#define UARTBIN_HEADER_SIZE 8u
Iki SOF byte'indan sonraki header boyutu, byte cinsinden.
Definition at line 86 of file uartbin.h.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
UARTBIN_MAX_FRAME_OVERHEAD
#define UARTBIN_MAX_FRAME_OVERHEAD (2u + UARTBIN_HEADER_SIZE + UARTBIN_CRC_SIZE)
Her payload etrafina eklenen byte'lar: SOF + header + CRC.
Examples
linux_posix_serial.c.
Definition at line 92 of file uartbin.h.
Referenced by uartbin_frame_len().
UARTBIN_SOF0
#define UARTBIN_SOF0 0xA5u
Start-of-frame dizisinin ilk byte'i.
Definition at line 80 of file uartbin.h.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
UARTBIN_SOF1
#define UARTBIN_SOF1 0x5Au
Start-of-frame dizisinin ikinci byte'i.
Definition at line 83 of file uartbin.h.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
UARTBIN_VERSION
#define UARTBIN_VERSION 1u
Her cerceve header'inda tasinan protokol surumu.
Definition at line 77 of file uartbin.h.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
UARTBINLIB_VERSION_MAJOR
#define UARTBINLIB_VERSION_MAJOR 1u
Kutuphane semantik versiyon major degeri.
Definition at line 65 of file uartbin.h.
UARTBINLIB_VERSION_MINOR
#define UARTBINLIB_VERSION_MINOR 0u
Kutuphane semantik versiyon minor degeri.
Definition at line 68 of file uartbin.h.
UARTBINLIB_VERSION_PATCH
#define UARTBINLIB_VERSION_PATCH 0u
Kutuphane semantik versiyon patch degeri.
Definition at line 71 of file uartbin.h.
UARTBINLIB_VERSION_STRING
#define UARTBINLIB_VERSION_STRING "V1.0.0"
Kutuphane semantik versiyon metni.
Definition at line 74 of file uartbin.h.
Typedef Documentation
uartbin_config_t
typedef struct uartbin_config uartbin_config_t
uartbin context baslatmak icin kullanilan konfigurasyon.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
uartbin_error_fn
typedef void(* uartbin_error_fn) (uartbin_error_t error, void *user)
Parser protokol hatasi veya timeout algiladiginda cagrilir.
Hata bildirildikten sonra parser SOF arama durumuna resetlenir ve sonraki byte'larda yeniden senkron olmaya calisir.
Parameters
error Hata kodu.
user uartbin_config icinden gelen kullanici pointer'i.
Definition at line 219 of file uartbin.h.
uartbin_error_t
typedef enum uartbin_error uartbin_error_t
uartbin_error_fn ile iletilen parser/runtime hatalari.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
uartbin_packet_fn
typedef void(* uartbin_packet_fn) (const uartbin_packet_t *packet, void *user)
Tam cerceve CRC dogrulamasindan gecince cagrilir.
Parameters
packet CRC kontrolunden gecmis paket metadata ve payload pointer'i.
user uartbin_config icinden gelen kullanici pointer'i.
Definition at line 208 of file uartbin.h.
uartbin_packet_t
typedef struct uartbin_packet uartbin_packet_t
Uygulamaya iletilen CRC kontrolunden gecmis paket.
Payload pointer uartbin_config::rx_payload_buffer alanini isaret eder. Ayni context uzerinde bir sonraki uartbin_feed(), uartbin_feed_at(), uartbin_feed_byte(), uartbin_feed_byte_at(), uartbin_poll() veya uartbin_reset() cagrimina kadar gecerlidir.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
uartbin_status_t
typedef enum uartbin_status uartbin_status_t
Hemen basarisiz olabilen API cagrilari icin donus durumlari.
uartbin_t
typedef struct uartbin uartbin_t
Tek uartbin linki icin runtime durum.
Her UART/protokol linki icin bir context ayir. Alanlar gizli allocation olmadan stack/statik ayirmaya izin vermek icin public'tir; fakat uygulama kodu bunlari internal detay gibi kabul etmelidir.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
uartbin_write_fn
typedef int(* uartbin_write_fn) (const uint8_t *data, size_t len, void *user)
uartbin_send() tarafindan kullanilan platform write hook'u.
Hook, donmeden once len byte'in tamamini yazmali veya kopyalamalidir. Bu onemlidir; cunku uartbin_send() tek cerceve icin hook'u birden fazla kez cagirabilir. Non-blocking UART TX icin bu hook'u uygulama TX kuyruguna kopyalayacak ve byte'lar kabul edildiyse basari dondurecek sekilde yaz.
Parameters
data Gonderilecek byte'lar.
len Gonderilecek byte sayisi.
user uartbin_config icinden gelen kullanici pointer'i.
Returns
Basarida 0, hatada sifir disi.
Definition at line 200 of file uartbin.h.
Enumeration Type Documentation
uartbin_error
enum uartbin_error
uartbin_error_fn ile iletilen parser/runtime hatalari.
Enumerator
UARTBIN_ERROR_BAD_VERSION
Cerceve desteklenmeyen protokol surumu kullandi.
UARTBIN_ERROR_BAD_LENGTH
Payload uzunlugu ayarlanan RX payload buffer'dan buyuk.
UARTBIN_ERROR_CRC
Cerceve CRC degeri alinan header ve payload ile eslesmedi.
UARTBIN_ERROR_RX_OVERFLOW
Payload alindi fakat RX payload buffer ayarlanmamis.
UARTBIN_ERROR_TIMEOUT
RX state machine rx_timeout_ms suresinden uzun sure cerceve icinde kaldi.
UARTBIN_ERROR_RETRY_EXHAUSTED
Response gelmeden guvenilir TX retry limitine ulasildi.
UARTBIN_ERROR_RETRY_WRITE
Guvenilir TX retry ayarlanan hook ile yazilamadi.
Definition at line 139 of file uartbin.h.
uartbin_status
enum uartbin_status
Hemen basarisiz olabilen API cagrilari icin donus durumlari.
Enumerator
UARTBIN_OK
Islem basariyla tamamlandi.
UARTBIN_EINVAL
Gecersiz arguman; NULL context veya eksik payload pointer gibi.
UARTBIN_EWRITE
Ayarlanan write hook TX hatasi bildirdi.
UARTBIN_EPAYLOAD_TOO_LONG
Daha kati TX payload limiti ekleyen uygulamalar icin ayrildi.
UARTBIN_ENO_BUFFER
Gerekli buffer'i olmayan konfigurasyonlar icin ayrildi.
UARTBIN_EBUSY
Guvenilir request/event zaten response bekliyor.
Definition at line 116 of file uartbin.h.
Function Documentation
uartbin_cancel_retry()
void uartbin_cancel_retry (uartbin_t * ctx)
Pending otomatik retry durumunu iptal et.
RX parsing resetlenmez ve bir sey gonderilmez. Uygulama response gelmeden bir istegi bilincli olarak terk etmek istediginde kullanislidir.
Parameters
ctx Baslatilmis context.
Definition at line 313 of file uartbin.c.
References uartbin_clear_retry().
uartbin_crc16_ccitt()
uint16_t uartbin_crc16_ccitt (const uint8_t * data, size_t len, uint16_t seed)
CRC-16/CCITT-FALSE degerini guncelle.
Polynomial: 0x1021. Kutuphane cerceveler icin 0xFFFF seed kullanir.
Parameters
data Giris byte'lari. Yalnizca len 0 iken NULL olabilir.
len Giris byte sayisi.
seed Baslangic/akan CRC degeri.
Returns
Guncellenmis CRC degeri.
Definition at line 320 of file uartbin.c.
Referenced by uartbin_build_frame(), uartbin_feed_byte_at(), and uartbin_send().
uartbin_feed()
void uartbin_feed (uartbin_t * ctx, const uint8_t * data, size_t len)
Alinan byte'lari timeout timestamp guncellemesi olmadan besle.
Zaman asimi yonetimi acikken uartbin_feed_at() tercih edilmelidir.
Parameters
ctx Baslatilmis context.
data Alinan byte buffer'i.
len Alinan byte sayisi.
Definition at line 490 of file uartbin.c.
References uartbin_feed_byte().
uartbin_feed_at()
void uartbin_feed_at (uartbin_t * ctx, const uint8_t * data, size_t len, uint32_t now_ms)
Alinan byte'lari gecerli uygulama timestamp degeri ile besle.
Parameters
ctx Baslatilmis context.
data Alinan byte buffer'i.
len Alinan byte sayisi.
now_ms HAL_GetTick() gibi monotonic milisaniye timestamp.
Examples
linux_posix_serial.c, and stm32_hal_dma_idle.c.
Definition at line 506 of file uartbin.c.
References uartbin_feed_byte_at().
Referenced by linux_uartbin_run(), and stm32_uartbin_dma_rx_event_callback().
uartbin_feed_byte()
void uartbin_feed_byte (uartbin_t * ctx, uint8_t byte)
Tek alinan byte'i timeout timestamp guncellemesi olmadan besle.
Zaman asimi yonetimi acikken uartbin_feed_byte_at() tercih edilmelidir.
Parameters
ctx Baslatilmis context.
byte Alinan byte.
Definition at line 501 of file uartbin.c.
References uartbin::last_rx_time_ms, and uartbin_feed_byte_at().
Referenced by uartbin_feed().
uartbin_feed_byte_at()
void uartbin_feed_byte_at (uartbin_t * ctx, uint8_t byte, uint32_t now_ms)
Tek alinan byte'i gecerli uygulama timestamp degeri ile besle.
RX state machine'e tek byte besle.
Parameters
ctx Baslatilmis context.
byte Alinan byte.
now_ms HAL_GetTick() gibi monotonic milisaniye timestamp.
Tek alinan byte'i gecerli uygulama timestamp degeri ile besle.
Bu internal state machine parser'in merkezidir. Public fonksiyon tum mantigi tek yerde tutar; boylece block ve byte feed yollari ayni davranir.
Examples
stm32_hal_interrupt.c.
Definition at line 533 of file uartbin.c.
References uartbin::cfg, uartbin::crc, uartbin::crc_bytes, uartbin::crc_pos, uartbin_packet::flags, uartbin::header, uartbin::header_pos, uartbin::last_rx_time_ms, uartbin_config::on_packet, uartbin_packet::payload, uartbin::payload_len, uartbin_packet::payload_len, uartbin::payload_pos, uartbin::retry_active, uartbin::retry_seq, uartbin_config::rx_payload_buffer, uartbin_config::rx_payload_capacity, uartbin_packet::seq, uartbin::state, uartbin_packet::type, uartbin_clear_retry(), uartbin_crc16_ccitt(), UARTBIN_CRC_SIZE, UARTBIN_ERROR_BAD_LENGTH, UARTBIN_ERROR_BAD_VERSION, UARTBIN_ERROR_CRC, UARTBIN_ERROR_RX_OVERFLOW, UARTBIN_FLAG_RESPONSE, uartbin_get_u16_le(), UARTBIN_HEADER_SIZE, uartbin_poll_rx_timeout(), uartbin_report_error(), uartbin_reset_rx(), UARTBIN_SOF0, UARTBIN_SOF1, UARTBIN_STATE_CRC, UARTBIN_STATE_HEADER, UARTBIN_STATE_PAYLOAD, UARTBIN_STATE_SOF0, UARTBIN_STATE_SOF1, UARTBIN_VERSION, and uartbin_config::user.
Referenced by stm32_uartbin_it_rx_complete_callback(), uartbin_feed_at(), and uartbin_feed_byte().
uartbin_init()
void uartbin_init (uartbin_t * ctx, const uartbin_config_t * config)
uartbin context baslat.
Parameters
ctx Baslatilacak context. Link kullanildigi surece gecerli kalmalidir.
config ctx icine kopyalanacak konfigurasyon.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Definition at line 295 of file uartbin.c.
References uartbin::cfg, and uartbin_reset_rx().
Referenced by linux_uartbin_init(), stm32_uartbin_dma_init(), and stm32_uartbin_it_init().
uartbin_next_seq()
uint16_t uartbin_next_seq (uartbin_t * ctx)
Bu context icin sonraki sifir olmayan TX sira numarasini dondur.
Bu daha cok otomatik uretilecek request'i gondermeden once takip etmek isteyen uygulamalar icin kullanislidir. Request/event yardimcilari bunu internal olarak cagirir; cogu uygulamanin dogrudan kullanmasi gerekmez.
Parameters
ctx Baslatilmis context.
Returns
Sonraki sira numarasi; ctx NULL ise 0.
Definition at line 385 of file uartbin.c.
References uartbin::tx_seq.
Referenced by uartbin_send_event(), and uartbin_send_request().
uartbin_poll()
void uartbin_poll (uartbin_t * ctx, uint32_t now_ms)
RX timeout ve opsiyonel TX retry zamanlamasini servis et.
uartbin_config::rx_timeout_ms veya uartbin_config::tx_retry_timeout_ms sifir disi oldugunda bunu main loop veya scheduler icinden periyodik cagir. Feed fonksiyonlari yalnizca RX timeout servis eder; otomatik TX retry bu acik poll cagrisi ile surulur.
Parameters
ctx Baslatilmis context.
now_ms Monotonic milisaniye timestamp.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Definition at line 517 of file uartbin.c.
References uartbin_poll_retry(), and uartbin_poll_rx_timeout().
Referenced by linux_uartbin_run(), stm32_uartbin_dma_poll(), and stm32_uartbin_it_poll().
uartbin_reset()
void uartbin_reset (uartbin_t * ctx)
Yalnizca RX parser durumunu resetle.
Platform UART hatalari, manuel abort veya link recovery olaylarindan sonra kullan. Konfigurasyon ve callback'ler korunur.
Parameters
ctx Resetlenecek context.
Examples
linux_posix_serial.c, stm32_hal_dma_idle.c, and stm32_hal_interrupt.c.
Definition at line 306 of file uartbin.c.
References uartbin_reset_rx().
Referenced by linux_uartbin_run(), stm32_uartbin_dma_error_callback(), stm32_uartbin_dma_rx_event_callback(), stm32_uartbin_it_error_callback(), and stm32_uartbin_it_rx_complete_callback().
uartbin_send()
uartbin_status_t uartbin_send (uartbin_t * ctx, uint8_t type, uint8_t flags, uint16_t seq, const uint8_t * payload, uint16_t payload_len)
Tek cerceveli paketi olustur ve gonder.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan paket tipi.
flags Uygulama tarafindan tanimlanan flag'ler.
seq Uygulama tarafindan tanimlanan sira numarasi.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 339 of file uartbin.c.
References uartbin_crc16_ccitt(), UARTBIN_CRC_SIZE, UARTBIN_EINVAL, UARTBIN_HEADER_SIZE, UARTBIN_OK, uartbin_put_u16_le(), UARTBIN_SOF0, UARTBIN_SOF1, UARTBIN_VERSION, and uartbin_write_all().
Referenced by uartbin_send_event(), uartbin_send_request(), and uartbin_send_response().
uartbin_send_event()
uartbin_status_t uartbin_send_event (uartbin_t * ctx, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile unsolicited event gonder.
Yardimci flags icine UARTBIN_FLAG_EVENT OR eder ve context'in internal sira sayacini kullanir. Peer event'i ACK'liyorsa response icinde bu paketin sira numarasini geri yazmalidir.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan event tipi.
flags Event flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Examples
linux_posix_serial.c.
Definition at line 454 of file uartbin.c.
References uartbin_check_retry_start(), uartbin_clear_retry(), UARTBIN_EINVAL, UARTBIN_FLAG_EVENT, uartbin_next_seq(), UARTBIN_OK, uartbin_send(), and uartbin_start_retry().
Referenced by main().
uartbin_send_request()
uartbin_status_t uartbin_send_request (uartbin_t * ctx, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Otomatik uretilen sira numarasi ile yeni request gonder.
Yardimci flags icine UARTBIN_FLAG_REQUEST OR eder ve context'in internal sira sayacini kullanir. Bu paketi cevaplamak icin response yardimcisini kullan.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
type Uygulama tarafindan tanimlanan request tipi.
flags Request flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Definition at line 399 of file uartbin.c.
References uartbin_check_retry_start(), uartbin_clear_retry(), UARTBIN_EINVAL, UARTBIN_FLAG_REQUEST, uartbin_next_seq(), UARTBIN_OK, uartbin_send(), and uartbin_start_retry().
uartbin_send_response()
uartbin_status_t uartbin_send_response (uartbin_t * ctx, const uartbin_packet_t * request, uint8_t type, uint8_t flags, const uint8_t * payload, uint16_t payload_len)
Alinan paketteki sira numarasini kullanarak response gonder.
Yardimci flags icine UARTBIN_FLAG_RESPONSE OR eder ve request->seq degerini geri yazar. Context sira sayacini ilerletmez.
Parameters
ctx Gecerli write hook'a sahip baslatilmis context.
request Cevaplanan paket.
type Uygulama tarafindan tanimlanan response tipi.
flags Response flag'i ile birlestirilecek uygulama flag'leri.
payload Payload byte'lari; payload_len 0 ise NULL olabilir.
payload_len Payload byte sayisi.
Returns
Basarida UARTBIN_OK, aksi halde hata durumu.
Examples
linux_posix_serial.c.
Definition at line 435 of file uartbin.c.
References uartbin_packet::seq, UARTBIN_EINVAL, UARTBIN_FLAG_RESPONSE, and uartbin_send().
Referenced by linux_uartbin_on_packet().